In [9]:
# creating matrix using list
mat = [[1,2,3],[1,2,3],[1,2,3]]
for i in range(len(mat)):
    for j in range(len(mat[i])):
        print(mat[i][j])
print(mat[i][j])
print(mat[0][0])
print(mat[0][1])
print(mat[0][2])

1
2
3
1
2
3
1
2
3
3
1
2
3


In [10]:
rows = int(input("Enter the number of rows: "))
col = int(input("Enter the number of columns: "))
mat = []
for i in range(rows):
    a = []
    for j in range(col):
        a.append(int(input()))
    mat.append(a)
for i in range(rows):
    for j in range(col):
        print(mat[i][j], end = " ")
    print()

Enter the number of rows: 2
Enter the number of columns: 3
1
2
3
4
5
6
1 2 3 
4 5 6 


In [11]:
matrix = [[col for col in range(4)] for row in range(4)]
print(matrix)

[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]


In [12]:
x = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
y = [[9, 8, 7],[6, 5, 4],[3, 2, 1]]


[[1, 2, 3], [4, 5, 6], [7, 8, 9], [9, 8, 7], [6, 5, 4], [3, 2, 1]]


In [15]:
print(len(x[0]))


3


In [17]:
res = [[0]*3 for _ in range(3)]

for i in range(len(x)):
    for j in range(len(x[0])):
        res[i][j] = x[i][j] + y[i][j]

for r in res:
    print(r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [18]:
add_res = [[x[i][j] + y[i][j] for j in range(len(x[0]))] for i in range(len(x))]

In [19]:
add_res

[[10, 10, 10], [10, 10, 10], [10, 10, 10]]

In [20]:
# Matrix addition
add_res = [[x[i][j] + y[i][j] for j in range(len(x[0]))] for i in range(len(x))]

# Matrix subtraction
sub_res = [[x[i][j] - y[i][j] for j in range(len(x[0]))] for i in range(len(x))]


print("Matrix Addition:")
for row in add_res:
    print(row)

print("\nMatrix Subtraction:")
for row in sub_res:
    print(row)

Matrix Addition:
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]

Matrix Subtraction:
[-8, -6, -4]
[-2, 0, 2]
[4, 6, 8]


In [22]:
import numpy as np
arr = np.random.randint(1,10,size=(3,3))
print(arr)

[[4 8 6]
 [2 8 5]
 [7 1 4]]


In [28]:
import numpy as np

# Use a 2x2 square matrix to avoid errors in operations like inverse, determinant, etc.
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print("Addition:\n", np.add(x, y))
print("Subtraction:\n", np.subtract(x, y))
print("Element-wise Multiplication:\n", np.multiply(x, y))
print("Element-wise Division:\n", np.divide(x, y))
print("Dot Product:\n", np.dot(x, y))
print("Matrix Multiplication (matmul):\n", np.matmul(x, y))
print("Transpose of x:\n", np.transpose(x))
print("Inverse of x:\n", np.linalg.inv(x))
print("Determinant of x:\n", np.linalg.det(x))
print("Rank of x:\n", np.linalg.matrix_rank(x))
print("Eigenvalues and Eigenvectors of x:\n", np.linalg.eig(x))
print("Singular Value Decomposition (SVD) of x:\n", np.linalg.svd(x))
print("Cholesky Decomposition of x + I:\n", np.linalg.cholesky(x + np.eye(2)))  # x must be positive-definite
print("QR Decomposition of x:\n", np.linalg.qr(x))
print("Solve Ax = y:\n", np.linalg.solve(x, y))
print("Least Squares solution:\n", np.linalg.lstsq(x, y, rcond=None))
print("Pseudo-inverse of x:\n", np.linalg.pinv(x))
print("Norm of x:\n", np.linalg.norm(x))
print("Condition number of x:\n", np.linalg.cond(x))
print("Sign and log(det(x)):\n", np.linalg.slogdet(x))


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Element-wise Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Dot Product:
 [[19 22]
 [43 50]]
Matrix Multiplication (matmul):
 [[19 22]
 [43 50]]
Transpose of x:
 [[1 3]
 [2 4]]
Inverse of x:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of x:
 -2.0000000000000004
Rank of x:
 2
Eigenvalues and Eigenvectors of x:
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
Singular Value Decomposition (SVD) of x:
 SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))
Cholesky Decomposition of x + I:
 [[1.41421356 0.        ]
 [2.12132034 0.70710678]]
QR Decomposition of x:
 QRResult(Q=array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777